AttachSpec("spec");                                          
K<nu> := QuadraticField(2);
R<t,x> := PolynomialRing(K,2);
ZK := Integers(K);
epsilon := FundamentalUnit(ZK);
f := 5*x^3 - 2*epsilon^7*t*x;
f_red, abc := reducemodel_units(f);
f_red;
f;
places := InfinitePlaces(K);
a := abc[1];
v := places[1];
[Log(AbsoluteValue(Evaluate(el,v)))/Log(AbsoluteValue(Evaluate(epsilon,v))) : el in abc];
f;
f_red;
f_naive := reducemodel_units_naive(f);
#Sprint(f);
#Sprint(f_red);
#Sprint(f_naive);
